### Load libraries

In [1]:
import pandas as pd

In [2]:
data = pd.read_excel('data.xlsx', sheet_name = 'Bajo')
data.head()

,Irrigation,Manure,Replication,PlantHeight,StemsPerPlant,StemDiameter,FreshWeight,StandingPlants
0,I1,M1,1,21.887500,7.625,7.855000,51.25,4.0
1,I1,M2,1,28.500000,9.625,10.432500,81.75,4.0
2,I1,M3,1,20.916667,6.000,6.233333,25.00,3.0
3,I1,M4,1,39.850000,11.500,16.272000,90.60,10.0
4,I2,M1,1,39.850000,11.500,18.272000,123.00,10.0

In [3]:
# Fresh Yield Calculations (ton/acre)
data['FreshPlot'] = data['FreshWeight'] * data['StandingPlants']
data['FreshYield'] = (data['FreshPlot']/2*4047)/1000000

In [5]:
data.head()

,Irrigation,Manure,Replication,PlantHeight,StemsPerPlant,StemDiameter,FreshWeight,StandingPlants,FreshPlot,FreshYield
0,I1,M1,1,21.887500,7.625,7.855000,51.25,4.0,205.0,0.414818
1,I1,M2,1,28.500000,9.625,10.432500,81.75,4.0,327.0,0.661685
2,I1,M3,1,20.916667,6.000,6.233333,25.00,3.0,75.0,0.151762
3,I1,M4,1,39.850000,11.500,16.272000,90.60,10.0,906.0,1.833291
4,I2,M1,1,39.850000,11.500,18.272000,123.00,10.0,1230.0,2.488905

In [6]:
#Descriptive statistics of the whole dataset
data.describe()

,Replication,PlantHeight,StemsPerPlant,StemDiameter,FreshWeight,StandingPlants,FreshPlot,FreshYield
count,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000,48.000000
mean,2.000000,32.926488,10.737954,12.421478,116.333102,5.715278,697.712963,1.411822
std,0.825137,7.632259,2.820460,3.639075,60.904376,3.317686,627.434036,1.269613
min,1.000000,17.000000,5.816667,5.466667,25.000000,1.000000,75.000000,0.151762
25%,1.000000,27.812500,9.191667,9.945833,81.250000,2.916667,249.500000,0.504863
50%,2.000000,32.100000,10.600000,13.050000,107.000000,4.000000,437.500000,0.885281
75%,3.000000,37.902500,11.425000,14.335000,134.975000,10.000000,1049.000000,2.122651
max,3.000000,51.500000,20.400000,23.580000,304.600000,10.000000,3046.000000,6.163581

In [7]:
## Mean of Irrigation interval treatments
data.groupby(['Irrigation']).mean()

,Replication,PlantHeight,StemsPerPlant,StemDiameter,FreshWeight,StandingPlants,FreshPlot,FreshYield
Irrigation,,,,,,,,
I1,2.0,30.221875,9.647222,11.261181,78.950000,4.805556,376.611111,0.762073
I2,2.0,31.268500,10.399917,12.709333,115.179167,8.666667,1006.783333,2.037226
I3,2.0,39.149329,13.154398,14.732593,149.726852,5.916667,1019.935185,2.063839
I4,2.0,31.066250,9.750278,10.982806,121.476389,3.472222,387.522222,0.784151

In [8]:
## Standard deviation of irrigation interval treatments

data.groupby('Irrigation').std()

,Replication,PlantHeight,StemsPerPlant,StemDiameter,FreshWeight,StandingPlants,FreshPlot,FreshYield
Irrigation,,,,,,,,
I1,0.852803,6.394193,1.841930,3.438318,31.902736,3.233219,313.001786,0.633359
I2,0.852803,5.089238,1.832765,3.038614,41.335850,1.969464,445.268911,0.901002
I3,0.852803,8.959603,3.913777,4.036162,83.520722,3.232177,933.507082,1.888952
I4,0.852803,6.695807,1.750261,3.097338,58.098979,2.512427,281.903743,0.570432

In [9]:
## Mean of manure treatments
data.groupby(['Manure']).mean()

,Replication,PlantHeight,StemsPerPlant,StemDiameter,FreshWeight,StandingPlants,FreshPlot,FreshYield
Manure,,,,,,,,
M1,2.0,30.994079,10.153704,11.574259,105.601852,5.555556,544.921296,1.102648
M2,2.0,33.280625,10.634444,11.897264,103.545833,5.750000,629.483333,1.273760
M3,2.0,31.658889,10.297972,11.854444,116.633333,5.305556,614.822222,1.244093
M4,2.0,35.772361,11.865694,14.359944,139.551389,6.250000,1001.625000,2.026788

In [10]:
## Standard deviation of Manure Rate treatments
data.groupby(['Manure']).std()

,Replication,PlantHeight,StemsPerPlant,StemDiameter,FreshWeight,StandingPlants,FreshPlot,FreshYield
Manure,,,,,,,,
M1,0.852803,8.893607,3.293161,4.139105,62.078485,3.172907,380.403780,0.769747
M2,0.852803,7.914277,2.207182,3.069428,43.037681,3.519427,512.954908,1.037964
M3,0.852803,5.743506,2.034846,2.985015,67.314892,3.251910,519.620613,1.051452
M4,0.852803,7.705436,3.485642,3.947965,68.698854,3.671141,930.281307,1.882424

In [11]:
data.groupby(['Irrigation', 'Manure']).std()

                   Replication  PlantHeight  StemsPerPlant  StemDiameter  \
Irrigation Manure
I1         M1              1.0     5.106512       1.793126      2.843471
           M2              1.0     5.933292       1.462090      3.162729
           M3              1.0     8.347211       2.673169      4.145089
           M4              1.0     5.422004       0.520416      1.554486
I2         M1              1.0     7.496657       2.720907      5.199366
           M2              1.0     4.185168       1.429452      3.285869
           M3              1.0     3.485116       1.017374      2.344099
           M4              1.0     7.211914       2.757414      2.532456
I3         M1              1.0    11.856092       5.103006      3.585119
           M2              1.0    12.455611       3.666982      3.816861
           M3              1.0     3.383745       1.452584      1.050397
           M4              1.0     9.558848       5.623101      6.104957
I4         M1              1.0     9.462371       2.349961      5.308826
           M2              1.0     8.380483       2.007924      2.832257
           M3              1.0     4.941083       1.127713      2.466399
           M4              1.0     5.147592       1.082247      2.009087

                   FreshWeight  StandingPlants    FreshPlot  FreshYield
Irrigation Manure
I1         M1        13.905065        3.906310   189.276498    0.383001
           M2        35.047337        3.464102   490.442997    0.992411
           M3        39.071516        1.000000   161.202771    0.326194
           M4        23.050018        4.618802   386.091095    0.781255
I2         M1        44.973474        0.577350   472.517809    0.956140
           M2        57.170272        0.000000   571.702720    1.156840
           M3        25.336551        3.055050   376.178840    0.761198
           M4        34.928689        1.154701   379.789012    0.768503
I3         M1       108.105286        0.000000   432.421143    0.875004
           M2        62.462155        1.000000   267.490187    0.541266
           M3        42.452012        1.732051   566.369149    1.146048
           M4       118.438589        4.041452  1471.504785    2.977590
I4         M1        25.626355        1.000000   176.153352    0.356446
           M2         8.650048        3.464102   363.392148    0.735324
           M3       119.948513        1.503083    29.584781    0.059865
           M4        15.340008        4.041452   496.232268    1.004126